/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "PosthogApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PrivateGithubLink": {
      "type": "sst.aws.TanstackStart"
      "url": string
    }
    "SentryDsn": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}